---
title: "Virtual Environments"
teaching: 0
exercises: 0
---

:::::::::::::::::::::::::::::::::::::: questions 

- What are are virtual environements and how are they used?
- How do I create and work with virtual environments in R?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

    - define the term virtual environment and explain how virtual environments are used
    - create a virtual environment that uses a specific version of a package using renv
    - restore a virtual environment using renv
    - explore the history of a virtual environment using renv

::::::::::::::::::::::::::::::::::::::::::::::::


::::::::::: challenge

Which of these statements are true?
1. Virtual environments are a tool for R only
2. Virtual environments can be used to share what packages you used with a collaborator
3. Virtual environments make sure all your packages are compatible versions
4. Virtual environments allow you to set a specific version of the package you want to use

::::::::::::::::::::::




::::::::::::::::::::::::::::::::::::: keypoints 

- Virtual environments help programmers to manage the packages installed in their workspace.
- In R, you can use the renv package to control the packages that are included in your environment.

::::::::::::::::::::::::::::::::::::::::::::::::

[r-markdown]: https://rmarkdown.rstudio.com/
